# Generated by Django 3.2.5 on 2023-05-15 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='category',
        ),
    ]
