# Generated by Django 3.2.5 on 2023-05-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymApp', '0002_remove_material_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
    ]
