# Generated by Django 4.2.1 on 2023-05-24 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymApp', '0004_members_package_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainermembers',
            name='trainer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gymApp.trainers'),
        ),
    ]
