# Generated by Django 4.2.1 on 2023-05-24 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymApp', '0005_trainermembers_trainer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerpackages',
            name='trainer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gymApp.trainers'),
        ),
    ]
